spring:
  application:
    name: projectTest
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project_test
    username: root
    password: green502
  data:
    redis:
      port: 6379
      host: localhost

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
    cache:
      disabled: true
server:
  port: 8080

file:
  directory: D:\2024-01\projectTest\petmilyTest\